stages:
  - Install_dependencies
  - run_pytest

Install_dependencies:
  tags:
    - cloud_governance
  stage: Install_dependencies
  script:
    - python -m pip install --upgrade pip
    - pip install flake8 pytest pytest-cov
    - if [[ -f requirements.txt ]]; then pip install -r requirements.txt; fi
    - if [[ -f tests_requirements.txt ]]; then pip install -r tests_requirements.txt; fi
  environment: testing

run_pytest:
  tags:
    - cloud_governance
  stage: run_pytest
  script:
    - ls
    - pytest -v tests/unittest/
  environment: testing
