run_pytest:
  tags:
    - docker
    - cloud_governance
  image: python:3.9
  stage: run_pytest
  before_script:
    - apt-get update && apt-get install build-essential python3-dev libldap2-dev libsasl2-dev -y -q
  script:
    pytest -v tests/unittest/

