run_pytest:
  tags:
    - docker
    - cloud_governance
  image: python:3.9
  stage: run_pytest
  cache:
    paths:
      - .venv/
  before_script:
    - apt-get update && apt-get install -y build-essential python3-dev libldap2-dev libsasl2-dev
  script:
    - pip install pytest
    - pytest --maxfail=2 -v tests/unittest/


