stages:
  - Install_dependencies
  - run_pytest

Install_dependencies:
  tags:
    - cloud_governance
  stage: Install_dependencies
  script:
    - python3 -m pip3 install --upgrade pip3
    - pip3 install flake8 pytest pytest-cov
    - if [[ -f requirements.txt ]]; then pip3 install -r requirements.txt; fi
    - if [[ -f tests_requirements.txt ]]; then pip3 install -r tests_requirements.txt; fi
  environment: testing

run_pytest:
  tags:
    - cloud_governance
  stage: run_pytest
  script:
    - ls
    - pytest -v tests/unittest/
  environment: testing
