name: Demonstration
on:
  push:
    branches: [ main ]

jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - name: step0
        run: |
          start=$(printf '%(%s)T' -1)
          sleep 60
          end=$(printf '%(%s)T' -1)
          ci_minutes_time=$(( (end - start) / 60))
          echo "ACTION=$ci_minutes_time" >> "$GITHUB_ENV"
      - id: step1
        run: |
          echo ACTION
          echo $ACTION
          echo "::set-output name=test::$ACTION"
      - id: step2
        run: echo "::set-output name=test::world"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
