name: Podman test
on:
  workflow_dispatch:

jobs:
  bundle:
    runs-on: macos-latest
    steps:
      - name: Create container
        run: |
          brew install podman
          podman machine init
          podman machine start
          podman info
          cat <<EOF | sudo podman build -t test-container -f - .
          FROM fedora:36
          RUN echo test
          EOF
