# Nightly CI https://github.com/marketplace/actions/deploy-nightly
# https://crontab.guru/
# This is a nightly CI Pipeline against Performance environment using IPI installer - run on Sunday
name: Deploy Operator Perf Env Nightly CI
# Only trigger, when the build workflow succeeded
#on:
#  workflow_run:
#    workflows: ["Deploy IPI Perf Env Nightly CI"]
#    types:
#      - completed
#on:
#  schedule:
#    - cron: '0 4 * * 0' # run on Sunday at 4 AM UTC/ 0 AM EDT
on:
  push:
    branches: [ main ]

# Ensures that only one deploy task per branch/environment will run at a time.
concurrency:
  group: performance-environment
  cancel-in-progress: false
  
jobs:
    
  ocp_operator_installation:
    name: OCP Operator Installation
    runs-on: ubuntu-latest
    outputs:
      install_resource_time_output: ${{ steps.ocp_install_resource_step.outputs.install_resource_time }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install latest benchmark-runner
        run: |
          python -m pip install --upgrade pip
          pip install benchmark-runner
      - name: ⚙️ SET SSH key
        env:
          PERF_PROVISION_PRIVATE_KEY: ${{ secrets.PERF_PROVISION_PRIVATE_KEY }}
          PERF_PROVISION_KNOWN_HOSTS: ${{ secrets.PERF_PROVISION_KNOWN_HOSTS }}
          RUNNER_PATH: ${{ secrets.RUNNER_PATH }}
          PERF_PROVISION_IP: ${{ secrets.PERF_PROVISION_IP }}
          PERF_PROVISION_USER: ${{ secrets.PERF_PROVISION_USER }}
        run: |
          mkdir -p "$RUNNER_PATH/.ssh/"
          echo "$PERF_PROVISION_PRIVATE_KEY" > $RUNNER_PATH/private_key.txt
          sudo chmod 600 $RUNNER_PATH/private_key.txt
          #echo "$PERF_PROVISION_KNOWN_HOSTS" > "$RUNNER_PATH/.ssh/known_hosts"
          echo "PERF_PROVISION_PRIVATE_KEY_PATH=$RUNNER_PATH/private_key.txt" >> "$GITHUB_ENV"
      - name: ⚙ Set Kubeconfig after OCP installation
        env:
          KUBECONFIG: ${{ secrets.PERF_KUBECONFIG }}
          RUNNER_PATH: ${{ secrets.RUNNER_PATH }}
        run: |
          mkdir -p "$RUNNER_PATH/.kube/"
          echo "$KUBECONFIG" > "$RUNNER_PATH/.kube/config"
          echo "KUBECONFIG_PATH=$RUNNER_PATH/.kube/config" >> "$GITHUB_ENV"
      - name: ☉ OCP Operator Reources install
        env:
          IBM_API_KEY: ${{ secrets.IBM_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          PERF_WORKER_IDS: ${{ secrets.PERF_WORKER_IDS }}
          PERF_PROVISION_IP: ${{ secrets.PERF_PROVISION_IP }}
          PERF_PROVISION_USER: ${{ secrets.PERF_PROVISION_USER }}
          PERF_PROVISION_OC_USER: ${{ secrets.PERF_PROVISION_OC_USER }}
          PERF_PROVISION_PORT: ${{ secrets.PERF_PROVISION_PORT }}
          GITHUB_REPOSITORY_SHORT: ${{ secrets.GIT_REPOSITORY_SHORT }}
          CONTAINER_KUBECONFIG_PATH: ${{ secrets.CONTAINER_KUBECONFIG_PATH }}
          CONTAINER_PRIVATE_KEY_PATH: ${{ secrets.CONTAINER_PRIVATE_KEY_PATH }}
          KUBEADMIN_PASSWORD: ${{ secrets.PERF_KUBEADMIN_PASSWORD }}
        run: |
          build=$(pip freeze | grep benchmark-runner | sed 's/==/=/g')
          build_version="$(cut -d'=' -f2 <<<"$build")"
          start=$(printf '%(%s)T' -1)
          echo '>>>>>>>>>>>>>>>>>>>>>>>>>> Start OCP Resource Install >>>>>>>>>>>>>>>>>>>>>>>>>>>>'
          #podman run --rm -e OCP_ENV_FLAVOR="PERF" -e IBM_API_KEY="$IBM_API_KEY" -e GITHUB_TOKEN="$GITHUB_TOKEN" -e KUBEADMIN_PASSWORD="$KUBEADMIN_PASSWORD" -e INSTALL_OCP_RESOURCES="True" -e CNV_VERSION="4.8.2" -e OCS_VERSION="4.8" -e NUM_OCS_DISK="4" -e INSTALL_RESOURCES_LIST="['cnv', 'local_storage', 'ocs', 'kata']" -e PERF_WORKER_IDS="$PERF_WORKER_IDS" -e PERF_PROVISION_IP="$PERF_PROVISION_IP" -e CONTAINER_PRIVATE_KEY_PATH="$CONTAINER_PRIVATE_KEY_PATH" -e PERF_PROVISION_USER="$PERF_PROVISION_USER" -e PERF_PROVISION_OC_USER="$PERF_PROVISION_OC_USER" -e PERF_PROVISION_PORT="$PERF_PROVISION_PORT" -e GITHUB_REPOSITORY_SHORT="$GITHUB_REPOSITORY_SHORT" -e PERF_PROVISION_TIMEOUT="3600" -e log_level="INFO" -v "$PERF_PROVISION_PRIVATE_KEY_PATH":"$CONTAINER_PRIVATE_KEY_PATH" -v "$KUBECONFIG_PATH":"$CONTAINER_KUBECONFIG_PATH" --privileged "quay.io/ebattat/benchmark-runner:v$build_version"
          echo '>>>>>>>>>>>>>>>>>>>>>>>>>> End OCP Resource Install   >>>>>>>>>>>>>>>>>>>>>>>>>>>>'
          sleep 60
          end=$(printf '%(%s)T' -1)
          echo "INSTALL_OCP_RESOURCE_MINUTES_TIME=$(( (( end - start )) / 60))" >> "$GITHUB_ENV"
      - id: ocp_install_resource_step
        run: echo "::set-output name=install_resource_time::$INSTALL_OCP_RESOURCE_MINUTES_TIME"

  nightly_start:
    name: Deploy Perf Nightly - Start
    runs-on: ubuntu-latest
    needs: [ocp_operator_installation]
    outputs:
      output_start_time: ${{ steps.nightly_start_step.outputs.output_start_time }}
    steps:
    - uses: actions/checkout@v2
    - id: nightly_start_step
      run: | 
        echo "::set-output name=output_start_time::$(printf '%(%s)T' -1)"
        echo ${{needs.ocp_operator_installation.outputs.install_resource_time_output}}
